package com.eternaljust.msea.utils

object RouteName {
    const val HOME = "home"
    const val NOTICE = "notice"
    const val NODE = "node"
    const val TOPIC_DETAIL = "topic_detail"
    const val PROFILE_TOPIC = "profile_topic"
    const val PROFILE_FRIEND = "profile_friend"
    const val PROFILE_FAVORITE = "profile_favorite"
    const val PROFILE_CREDIT = "profile_credit"
    const val PROFILE_GROUP= "profile_group"
    const val SETTING = "setting"
    const val ABOUT = "about"
    const val ABOUT_LICENSE = "about_license"
    const val ABOUT_SOURCE_CODE = "about_source_code"
    const val ABOUT_SDK_LIST = "about_sdk_list"
    const val LOGIN = "login"
    const val LOGOUT= "logout"
    const val SIGN = "sign"
    const val TAG = "tag"
    const val TAG_LIST = "tag_list"
    const val NODE_LIST = "node_list"
    const val TERMS_OF_SERVICE = "terms_of_service"
    const val WEBVIEW = "webview"
    const val LICENSE = "license"
    const val SOURCE_CODE = "source_code"
    const val SDK_LIST = "sdk_list"
}